retain_public: true
disable_unused_import_analysis: true
retain_files:
  - Tests/**

targets:
  - CoreFP
  - CoreFPOperators
  - DataStructure
  - DataStructureOperators
  - FP
  - CoreFPTests
  - CoreFPOperatorsTests
  - DataStructureTests
  - DataStructureOperatorsTests
