version: 1
builder:
  configs:
    - platform: macosSpm
      documentation_targets:
        - FP
        - CoreFP
        - CoreFPOperators
        - DataStructure
        - DataStructureOperators
    - platform: ios
    - platform: tvos
    - platform: watchos
    - platform: visionos
    - platform: linux
    - platform: windows
    - platform: android
