// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "FP",
    platforms: [
        .macOS(.v10_15),
        .iOS(.v13),
        .tvOS(.v13),
        .watchOS(.v6)
    ],
    products: [
        .library(name: "FP", targets: ["FP"]),
        .library(name: "ConcurrencyFP", targets: ["ConcurrencyFP"]),
        .library(name: "CombineFP", targets: ["CombineFP"]),
        .library(name: "Either", targets: ["Either"]),
        .library(name: "Reader", targets: ["Reader"]),
        .library(name: "Operators", targets: ["Operators"]),
        .library(name: "EitherOperators", targets: ["EitherOperators"]),
        .library(name: "ReaderOperators", targets: ["ReaderOperators"]),
        .library(name: "CombineOperators", targets: ["CombineOperators"]),
        .library(name: "CombineEither", targets: ["CombineEither"]),
        .library(name: "ConcurrencyOperators", targets: ["ConcurrencyOperators"]),
        .library(name: "ReaderEither", targets: ["ReaderEither"]),
        .library(name: "ReaderEitherOperators", targets: ["ReaderEitherOperators"]),
        .library(name: "ReaderCombineFP", targets: ["ReaderCombineFP"]),
        .library(name: "ReaderCombineOperators", targets: ["ReaderCombineOperators"]),
        .library(name: "ReaderConcurrencyFP", targets: ["ReaderConcurrencyFP"]),
        .library(name: "ReaderConcurrencyOperators", targets: ["ReaderConcurrencyOperators"])
    ],
    targets: [
        .target(name: "FP"),
        .target(name: "ConcurrencyFP", dependencies: ["FP"]),
        .target(name: "CombineFP", dependencies: ["FP"]),
        .target(name: "Either", dependencies: ["FP"]),
        .target(name: "Reader", dependencies: ["FP"]),
        .target(name: "Operators", dependencies: ["FP"]),
        .target(name: "EitherOperators", dependencies: ["Either", "Operators"]),
        .target(name: "ReaderOperators", dependencies: ["Reader", "Operators"]),
        .target(name: "CombineOperators", dependencies: ["CombineFP", "Operators"]),
        .target(name: "CombineEither", dependencies: ["CombineFP", "Either"]),
        .target(name: "ConcurrencyOperators", dependencies: ["ConcurrencyFP", "Operators"]),
        .target(name: "ReaderEither", dependencies: ["Reader", "Either"]),
        .target(name: "ReaderEitherOperators", dependencies: ["ReaderEither", "Reader", "Either", "EitherOperators", "Operators"]),
        .target(name: "ReaderCombineFP", dependencies: ["Reader", "CombineFP"]),
        .target(name: "ReaderCombineOperators", dependencies: ["ReaderCombineFP", "Reader", "CombineFP", "CombineOperators", "Operators"]),
        .target(name: "ReaderConcurrencyFP", dependencies: ["Reader", "ConcurrencyFP"]),
        .target(name: "ReaderConcurrencyOperators", dependencies: ["ReaderConcurrencyFP", "Reader", "ConcurrencyFP", "ConcurrencyOperators", "Operators"]),
        .testTarget(name: "FPTests", dependencies: ["FP"]),
        .testTarget(name: "EitherTests", dependencies: ["Either", "FP"]),
        .testTarget(name: "ReaderTests", dependencies: ["Reader", "FP"]),
        .testTarget(name: "CombineFPTests", dependencies: ["CombineFP", "FP"]),
        .testTarget(name: "ConcurrencyFPTests", dependencies: ["ConcurrencyFP", "FP"]),
        .testTarget(name: "OperatorsTests", dependencies: ["Operators", "FP"]),
        .testTarget(name: "EitherOperatorsTests", dependencies: ["Either", "EitherOperators", "Operators", "FP"]),
        .testTarget(name: "ReaderOperatorsTests", dependencies: ["Reader", "ReaderOperators", "Operators", "FP"]),
        .testTarget(name: "CombineOperatorsTests", dependencies: ["CombineFP", "CombineOperators", "Operators", "FP"]),
        .testTarget(name: "ConcurrencyOperatorsTests", dependencies: ["ConcurrencyFP", "ConcurrencyOperators", "Operators", "FP"]),
        .testTarget(name: "CombineEitherTests", dependencies: ["CombineFP", "Either", "CombineEither", "FP"]),
        .testTarget(name: "ReaderEitherTests", dependencies: ["Reader", "Either", "ReaderEither", "FP"]),
        .testTarget(name: "ReaderEitherOperatorsTests", dependencies: ["Reader", "Either", "ReaderEither", "ReaderEitherOperators", "Operators", "EitherOperators", "FP"]),
        .testTarget(name: "ReaderCombineFPTests", dependencies: ["Reader", "CombineFP", "ReaderCombineFP", "FP"]),
        .testTarget(name: "ReaderCombineOperatorsTests", dependencies: ["Reader", "CombineFP", "ReaderCombineFP", "ReaderCombineOperators", "Operators", "CombineOperators", "FP"]),
        .testTarget(name: "ReaderConcurrencyFPTests", dependencies: ["Reader", "ConcurrencyFP", "ReaderConcurrencyFP", "FP"]),
        .testTarget(name: "ReaderConcurrencyOperatorsTests", dependencies: ["Reader", "ConcurrencyFP", "ReaderConcurrencyFP", "ReaderConcurrencyOperators", "Operators", "ConcurrencyOperators", "FP"])
    ]
)
