// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "FP",
    platforms: [
        .macOS(.v10_15),
        .iOS(.v13),
        .tvOS(.v13),
        .watchOS(.v6)
    ],
    products: [
        .library(name: "FP", targets: ["FP"]),
        .library(name: "Either", targets: ["Either"]),
        .library(name: "Reader", targets: ["Reader"]),
        .library(name: "Operators", targets: ["Operators"]),
        .library(name: "EitherOperators", targets: ["EitherOperators"]),
        .library(name: "ReaderOperators", targets: ["ReaderOperators"]),
        .library(name: "ReaderEither", targets: ["ReaderEither"]),
        .library(name: "ReaderEitherOperators", targets: ["ReaderEitherOperators"]),
        .library(name: "Stateful", targets: ["Stateful"]),
        .library(name: "StatefulOperators", targets: ["StatefulOperators"]),
        .library(name: "StatefulEither", targets: ["StatefulEither"]),
        .library(name: "StatefulEitherOperators", targets: ["StatefulEitherOperators"]),
        .library(name: "StatefulReader", targets: ["StatefulReader"]),
        .library(name: "StatefulReaderOperators", targets: ["StatefulReaderOperators"]),
        .library(name: "Writer", targets: ["Writer"]),
        .library(name: "WriterOperators", targets: ["WriterOperators"]),
        .library(name: "WriterEither", targets: ["WriterEither"]),
        .library(name: "WriterEitherOperators", targets: ["WriterEitherOperators"]),
        .library(name: "WriterReader", targets: ["WriterReader"]),
        .library(name: "WriterReaderOperators", targets: ["WriterReaderOperators"]),
        .library(name: "WriterStateful", targets: ["WriterStateful"]),
        .library(name: "WriterStatefulOperators", targets: ["WriterStatefulOperators"])
    ],
    targets: [
        .target(name: "FP"),
        .target(name: "Either", dependencies: ["FP"]),
        .target(name: "Reader", dependencies: ["FP"]),
        .target(name: "Operators", dependencies: ["FP"]),
        .target(name: "EitherOperators", dependencies: ["Either", "Operators"]),
        .target(name: "ReaderOperators", dependencies: ["Reader", "Operators"]),
        .target(name: "ReaderEither", dependencies: ["Reader", "Either"]),
        .target(name: "ReaderEitherOperators", dependencies: ["ReaderEither", "Reader", "Either", "EitherOperators", "Operators"]),
        .target(name: "Stateful", dependencies: ["FP"]),
        .target(name: "StatefulOperators", dependencies: ["Stateful", "Operators"]),
        .target(name: "StatefulEither", dependencies: ["Stateful", "Either"]),
        .target(name: "StatefulEitherOperators", dependencies: ["StatefulEither", "StatefulOperators", "EitherOperators"]),
        .target(name: "StatefulReader", dependencies: ["Stateful", "Reader"]),
        .target(name: "StatefulReaderOperators", dependencies: ["StatefulReader", "StatefulOperators", "ReaderOperators"]),
        .target(name: "Writer", dependencies: ["FP"]),
        .target(name: "WriterOperators", dependencies: ["Writer", "Operators"]),
        .target(name: "WriterEither", dependencies: ["Writer", "Either"]),
        .target(name: "WriterEitherOperators", dependencies: ["WriterEither", "WriterOperators", "EitherOperators"]),
        .target(name: "WriterReader", dependencies: ["Writer", "Reader"]),
        .target(name: "WriterReaderOperators", dependencies: ["WriterReader", "WriterOperators", "ReaderOperators"]),
        .target(name: "WriterStateful", dependencies: ["Writer", "Stateful"]),
        .target(name: "WriterStatefulOperators", dependencies: ["WriterStateful", "WriterOperators", "StatefulOperators"]),
        .testTarget(name: "FPTests", dependencies: ["FP"]),
        .testTarget(name: "EitherTests", dependencies: ["Either", "FP"]),
        .testTarget(name: "ReaderTests", dependencies: ["Reader", "FP"]),
        .testTarget(name: "OperatorsTests", dependencies: ["Operators", "FP"]),
        .testTarget(name: "EitherOperatorsTests", dependencies: ["Either", "EitherOperators", "Operators", "FP"]),
        .testTarget(name: "ReaderOperatorsTests", dependencies: ["Reader", "ReaderOperators", "Operators", "FP"]),
        .testTarget(name: "ReaderEitherTests", dependencies: ["Reader", "Either", "ReaderEither", "FP"]),
        .testTarget(name: "ReaderEitherOperatorsTests", dependencies: ["Reader", "Either", "ReaderEither", "ReaderEitherOperators", "Operators", "EitherOperators", "FP"]),
        .testTarget(name: "StatefulTests", dependencies: ["Stateful", "FP"]),
        .testTarget(name: "StatefulOperatorsTests", dependencies: ["Stateful", "StatefulOperators", "Operators", "FP"]),
        .testTarget(name: "StatefulEitherTests", dependencies: ["StatefulEither", "Stateful", "Either"]),
        .testTarget(name: "StatefulEitherOperatorsTests", dependencies: ["StatefulEither", "StatefulEitherOperators", "StatefulOperators", "EitherOperators"]),
        .testTarget(name: "StatefulReaderTests", dependencies: ["StatefulReader", "Stateful", "Reader"]),
        .testTarget(name: "StatefulReaderOperatorsTests", dependencies: ["StatefulReader", "StatefulReaderOperators", "StatefulOperators", "ReaderOperators"]),
        .testTarget(name: "WriterTests", dependencies: ["Writer", "FP"]),
        .testTarget(name: "WriterOperatorsTests", dependencies: ["Writer", "WriterOperators", "Operators", "FP"]),
        .testTarget(name: "WriterEitherTests", dependencies: ["WriterEither", "Writer", "Either"]),
        .testTarget(name: "WriterEitherOperatorsTests", dependencies: ["WriterEither", "WriterEitherOperators", "WriterOperators", "EitherOperators"]),
        .testTarget(name: "WriterReaderTests", dependencies: ["WriterReader", "Writer", "Reader"]),
        .testTarget(name: "WriterReaderOperatorsTests", dependencies: ["WriterReader", "WriterReaderOperators", "WriterOperators", "ReaderOperators"]),
        .testTarget(name: "WriterStatefulTests", dependencies: ["WriterStateful", "Writer", "Stateful"]),
        .testTarget(name: "WriterStatefulOperatorsTests", dependencies: ["WriterStateful", "WriterStatefulOperators", "WriterOperators", "StatefulOperators"])
    ]
)
