// SPDX-License-Identifier: Apache-2.0
/// A `CaseIterable` enum whose values can be compared against instances of `Subject`,
/// ignoring associated values.
///
/// Typically used as the nested `cases` enum generated by `@Prisms`: it mirrors the
/// case *names* of the annotated enum (no associated payloads) so callers can iterate
/// over them or ask whether a value is in a particular case.
public protocol CaseMatchable: CaseIterable, Sendable {
    associatedtype Subject

    /// Returns `true` when `self` names the same case as `value`, regardless of any
    /// associated payload `value` carries.
    func matches(_ value: Subject) -> Bool
}

/// A type whose case structure is mirrored by a companion `Cases` enum.
///
/// Conforming types get the `is(_:)` predicate for free via this protocol's
/// extension — no per-type code generation needed.
///
/// `@Prisms` adds this conformance automatically and generates the `Cases` enum
/// (named `cases`) inside the annotated enum.
public protocol HasCases: Sendable {
    associatedtype Cases: CaseMatchable where Cases.Subject == Self
}

public extension HasCases {
    /// Returns `true` when `self` is in the case named by `c`.
    ///
    /// ```swift
    /// @Prisms
    /// enum Shape {
    ///     case circle(Double)
    ///     case rectangle(Double, Double)
    /// }
    ///
    /// Shape.circle(3.14).is(.circle)    // true
    /// Shape.circle(3.14).is(.rectangle) // false
    /// ```
    func `is`(_ c: Cases) -> Bool { c.matches(self) }
}
