@_exported import CoreFP

/// Generates a memberwise initializer and a `lens` namespace for a struct.
///
/// Rules:
/// - `let name: T`      → required init parameter + reconstruction `Lens`
/// - `let name = value` → excluded from init, no `Lens` (immutable constant)
/// - `var name: T`      → required init parameter + `WritableKeyPath`-based `Lens`
/// - `var name: T = v`  → init parameter with default `v` + `WritableKeyPath`-based `Lens`
/// - Computed / lazy    → skipped
///
/// ```swift
/// @Lenses(init: .public)
/// struct Config {
///     let host: String
///     let version = 3       // constant — not in init, no lens
///     var port: Int
///     var timeout = 30
/// }
///
/// let c = Config(host: "localhost", port: 8080)
/// Config.lens.host.set(c, "example.com")   // reconstruction lens
/// Config.lens.port.set(c, 9090)            // WritableKeyPath lens
/// ```
@attached(member, names: arbitrary)
public macro Lenses(init access: LensesAccess = .internal) =
    #externalMacro(module: "FPMacrosPlugin", type: "LensesMacro")

/// Access modifier for the initializer and lens namespace generated by `@Lenses`.
public enum LensesAccess {
    case `private`, `internal`, `package`, `public`
}
