@_exported import CoreFP

/// Generates a memberwise initializer, a `lens` namespace, and a `with(...)` helper for
/// a struct.
///
/// By default (`@Lenses` or `@Lenses(.all)`) the macro emits:
/// - `init(...)` — a memberwise initializer.
/// - `Foo.lens.property` — a `Lens<Foo, Property>` per stored property, in a nested
///   `enum lens` namespace.
/// - `foo.with(property: ...)` — a copy-with-overrides helper that calls the init once,
///   collapsing the O(N²) reconstruction-closure footprint of the previous codegen to O(N).
///
/// ## Property rules
///
/// - `let name: T`      → required init parameter + reconstruction `Lens`
/// - `let name = value` → excluded from init, no `Lens` (immutable constant)
/// - `var name: T`      → required init parameter + `WritableKeyPath`-based `Lens`
/// - `var name: T = v`  → init parameter with default `v` + `WritableKeyPath`-based `Lens`
/// - Computed / lazy    → skipped
///
/// ## Visibility
///
/// The `lens` namespace and `with(...)` helper mirror the host struct's declared
/// visibility. Properties whose declared visibility is *lower* than the struct's are
/// silently skipped from both — Swift's access rules forbid exposing them via a more
/// visible API.
///
/// The init's visibility is configurable via `init access:` because an init can legally
/// assign lower-visibility properties (a `public init` may write `internal var port`).
///
/// ## Conflict detection
///
/// If the struct already declares an `init` with parameter labels matching what `@Lenses`
/// would generate, the macro skips its own init silently — the user's init wins. The
/// reconstruction lenses then resolve against the user's init (which must have those
/// same labels, or it wouldn't be a conflict in the first place).
///
/// ## Slicing the output
///
/// ```swift
/// @Lenses(.all)         // default — init + lens + with
/// @Lenses(.initOnly)    // only the memberwise init
/// @Lenses(.lensesOnly)  // lens + with, no init at all
/// ```
///
/// ## Example
///
/// ```swift
/// @Lenses(init: .public)
/// public struct Config {
///     public let host: String
///     public let version = 3       // constant — not in init, no lens
///     public var port: Int
///     public var timeout = 30
/// }
///
/// let c = Config(host: "localhost", port: 8080)
/// Config.lens.host.set(c, "example.com")
/// Config.lens.port.set(c, 9090)
/// c.with(port: 9090)               // same effect, no lens needed
/// ```
@attached(member, names: arbitrary)
public macro Lenses(
    _ emit: LensesEmit = .all,
    init access: LensesAccess = .internal
) = #externalMacro(module: "FPMacrosPlugin", type: "LensesMacro")

/// Controls which pieces `@Lenses` emits.
public enum LensesEmit: Sendable {
    /// Default — emit the memberwise init (if no conflicting init exists), the `lens`
    /// namespace, and the `with(...)` helper.
    case all
    /// Emit only the memberwise init. Skip the `lens` struct and `with(...)`.
    case initOnly
    /// Emit only the `lens` struct and `with(...)`. Never emit an init, even if the
    /// struct has no other init. Use when you want full control of initialization.
    case lensesOnly
}

/// Access modifier for the initializer generated by `@Lenses`.
///
/// The `lens` namespace and `with(...)` helper mirror the struct's declared
/// visibility — this parameter only controls the init.
public enum LensesAccess: Sendable {
    case `private`, `internal`, `package`, `public`
}
